# Generated by Django 4.1 on 2022-08-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_experience', models.TextField(help_text='Enter the work experience', max_length=1000)),
                ('education', models.TextField(help_text='Enter the background education', max_length=1000)),
            ],
        ),
    ]
