# Generated by Django 4.1 on 2022-08-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Address', models.TextField(help_text='Enter the address', max_length=1000)),
                ('Ph', models.TextField(help_text='Enter the phone number', max_length=100)),
            ],
        ),
    ]
