# Generated by Django 4.1 on 2022-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Ph',
            field=models.TextField(help_text='Enter the phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
