# Generated by Django 4.1 on 2022-08-31 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_location_ph_alter_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.TextField(help_text='Enter the price', max_length=10)),
                ('Description', models.TextField(help_text='Enter a brief description of the Course', max_length=1000)),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.teacher')),
                ('age_recommend', models.ManyToManyField(to='catalog.age_recommend')),
                ('category', models.ManyToManyField(to='catalog.category')),
                ('duration', models.ManyToManyField(to='catalog.duration')),
            ],
        ),
    ]
